COPY public."Matches" (id, "team1Id", "team2Id", "poolId", "roundId", status, "scoreTeam1", "scoreTeam2", type, "winnerTeamId", "loserTeamId", "createdAt", "updatedAt") FROM stdin;
COPY public."Pool" (id, "poolName", "bracketId", "tournamentId", "createdAt", "updatedAt") FROM stdin;
COPY public."PoolTeam" ("poolId", "teamId", "createdAt", "updatedAt") FROM stdin;
COPY public._prisma_migrations (id, checksum, finished_at, migration_name, logs, rolled_back_at, started_at, applied_steps_count) FROM stdin;
COPY public.bracketformats (id, name, description, "createdAt", "updatedAt") FROM stdin;
COPY public.brackets (id, name, "maxTeams", "minAge", "maxAge", "minRating", "maxRating", "bracketFormatId", "scoringListId", "playoffSeedingId", "playoffMatchId", "semiFinalMatchId", "bronzeMatchId", "goldMatchId", "roundId", "tournamentId", "eventId", "poolStarted", status, "startDate", "endDate", "registrationFee", "createdAt", "updatedAt", "scoringConfig", division) FROM stdin;
COPY public.clubs (id, name, location, "phoneNumber", "clubType", description, "hostId", "createdAt", "updatedAt") FROM stdin;
COPY public.events (id, "eventName", "createdAt", "updatedAt") FROM stdin;
COPY public.formats (id, name, "createdAt", "updatedAt") FROM stdin;
COPY public.groups (id, name, "createdAt", "updatedAt") FROM stdin;
COPY public.playerbrackets (id, "playerId", "tournamentId", "bracketId", status, "createdAt", "updatedAt") FROM stdin;
COPY public.playerregistrations (id, "playerId", "tournamentId", "bracketId", status, "paymentStatus", "checkInStatus", "checkInTime", "createdAt", "updatedAt", "paymentEmailSentCount", "clubName", "playerRole", "rosterNumber", division, "partnerId") FROM stdin;
COPY public.playoffseedings (id, name, description, "createdAt", "updatedAt") FROM stdin;
COPY public.poolteamstats (id, "poolId", "teamId", wins, losses, "pointsFor", "pointsAgainst", "pointDifference", "pdPercent", "playoffSeed", "playoffWins", "playoffPointsFor", "playoffPointsAgainst", "playoffPointDifference", "finalRank", "createdAt", "updatedAt") FROM stdin;
COPY public.roles (id, name, "createdAt", "updatedAt") FROM stdin;
COPY public.rounds (id, "poolId", "roundNumber", status, "bracketId", type, "createdAt", "updatedAt") FROM stdin;
COPY public.scoringlists (id, name, "createdAt", "updatedAt", rules) FROM stdin;
COPY public.teamplayers (id, "playerId", "teamId", role, "createdAt", "updatedAt") FROM stdin;
COPY public.teams (id, "teamName", "bracketId", "tournamentId", status, "paymentStatus", "isComplete", "createdAt", "updatedAt") FROM stdin;
COPY public.tournaments (id, name, description, "entryFee", discount, "tournamentTumbnail", location, "startDate", "endDate", "registrationOpenDate", "registrationCloseDate", status, "organizerInfo", slug, "clubId", "hostId", "createdAt", "updatedAt", venue, timezone, "refundDeadline", "refundFee", "duprRecorded", "duprEnforced", "requireSkillRating") FROM stdin;
COPY public.userroles (id, "userId", "roleId", "createdAt", "updatedAt") FROM stdin;
COPY public.users (id, firstname, lastname, email, password, provider, "providerId", "profilePicture", age, gender, "phoneNumber", "isVerified", "verificationToken", "passwordResetToken", "passwordResetExpires", "accountExpiresAt", "createdAt", "updatedAt", "tokenVersion", "duprId", facebook, instagram, "paymentMethod", "paymentStatus", "roleId", "duprRating") FROM stdin;
